[global]
  checkNewVersion = false
  sendAnonymousUsage = false

# Log rotations is not a traefik feature, but traefik will close and reopen
# log files on USR1 signal which allows for rotation via logrotate

[accessLog]
  filePath = "/data/access.log"

[log]
  level = "DEBUG"
  filePath = "/data/traefik.log"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

# Let's encrypt is an Automatic Certificate Management Environment (ACME) provider
[certificatesResolvers]
  [certificatesResolvers.lets-encrypt.acme]
    email = "martinklepsch@googlemail.com"
    storage = "/data/acme.json" # certs are written/tracked here
    keyType = "RSA2048"
    # Use this while testing, uncomment or delete after done
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    [certificatesResolvers.lets-encrypt.acme.httpChallenge]
      entryPoint = "web"

#[http.middlewares]
#  [http.middlewares.compress.compress]

#[http.routers]
#  [http.routers.cljdoc]
#    entryPoints = ["websecure"]
#    entryPoints = ["web"]
#    rule = "HostRegexp(`.*`)"
#    rule = "PathPrefix(`/`)"
#    rule = "Host(`cljdoc.org`, `cljdoc.xyz`)"
#    service = "cljdoc"
#    middlewares = ["compress"]
#    [http.routers.cljdoc.tls]
#      certResolver = "lets-encrypt"

[api]
[ping]

[providers.consulCatalog]
  prefix = "traefik"
  exposedByDefault = false
  watch = true
#  constraints = "Tag(`cljdoc`)"
