version: 2.1
jobs:
  #
  # build: back-end-checks
  #
  back-end-checks:
    docker:
      - image: cimg/clojure:1.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run:
          name: Validate our own cljdoc.edn
          command: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s doc/cljdoc.edn

      - run:
          name: Report Tools Versions
          command: |
            java --version
            clojure --version
            bb --version

      - run:
          name: Bring Down Clojure deps
          command: clojure -Spath

      - run:
          name: Lint
          command: bb lint

      - run:
          name: Code Style Check
          command: bb code-format check

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}

  #
  # build: front-end-checks
  #
  front-end-checks:
    docker:
      - image: cimg/node:16.4.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Report Tools Versions
          command: node --version

      - run:
          name: Install JavaScript Depedencies
          command: npm ci

      - run:
          name: Lint Front End Sourc
          command: npm run lint

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}

  #
  # build: test
  #
  test:
    docker:
      - image: cimg/clojure:1.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run:
          name: Report Tools Versions
          command: |
           java --version
           clojure --version

      - run:
          name: Bring Down Clojure deps
          command: clojure -Spath

      - run:
          name: Build Docs for Sample Library
          command: ./script/cljdoc ingest --project bidi --version 2.1.3

      - run:
          name: Run Tests
          command: clojure -M:test --reporter documentation

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}

  #
  # build: package, output used by:
  # - publish-zip-build
  # - publish-docker
  #
  package:
    docker:
      - image: cimg/node:16.4.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package-lock.json" }}
            - v1-npm-dependencies- # fallback if cache not found

      - run:
          name: Report Tools Versions
          command: |
            node --version

      - run:
          name: Install JavaScript Depedencies
          command: npm ci

      - run:
          name: Package cljdoc
          command: ./script/package

      # for publish-zip-build job
      - persist_to_workspace:
          root: .
          paths:
            - target

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}
  #
  # build - used later in workflow to group all build jobs
  #
  build:
    docker:
      - image: alpine
    steps:
      - run: echo build done

  #
  # deploy: publish-zip-build
  # (relies on output saved by package)
  #
  publish-zip-build:
    docker:
      - image: cimg/python:3.10
    steps:
      # from package job
      - attach_workspace:
          at: workspace
      - run: ls workspace

      - run:
          name: Install awscli
          command: pip3 install awscli

      - run:
          name: Tools Versions
          command: |
            pip3 --version
            aws --version

      - run:
          name: Set AWS env vars
          # vars are coming from terraform setup
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$RELEASES_BUCKET_ACCESS_KEY' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$RELEASES_BUCKET_SECRET_KEY' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Deploy to S3
          command: aws s3 sync workspace/target s3://$RELEASES_BUCKET_NAME/build-$CIRCLE_SHA1/ --delete

  #
  # deploy: make and image and publish to docker
  # (relies on output saved by package)
  #
  publish-docker:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      # from package job
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # because target/ has been put into place `make image` can be
      # run without running ./script/package (which would require npm)
      - run: cd ops/docker && make image
      - run: docker push --all-tags cljdoc/cljdoc

  # This assumes that an SSH key has been added to the CircleCI build
  # and it's public key has been copied to ~/.ssh/authorized_keys on
  # the production machine:
  # cat ~/.ssh/cljdoc_deploy.pub | ssh root@cljdoc.org 'cat >> .ssh/authorized_keys'
  deploy-to-nomad:
    docker:
      - image: cimg/clojure:1.11.1-node

    steps:
      - add_ssh_keys:
          fingerprints:
            - "75:fb:98:1f:f6:21:7f:bf:cc:c9:0e:b2:9e:be:5c:e8"
      - checkout
      - run: >
          cd modules/deploy &&
          clojure -M -m cljdoc.deploy deploy -t $(./../../script/version.sh) --nomad-ip $NOMAD_IP -k ~/.ssh/id_rsa_75fb981ff6217fbfccc90eb29ebe5ce8

workflows:
  build-and-deploy:
    jobs:
      - front-end-checks
      - back-end-checks
      - test
      - package
      - build:
          requires:
            - front-end-checks
            - back-end-checks
            - test
            - package
      - publish-docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish-zip-build:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-to-nomad:
          requires:
            - build
            - publish-docker
          filters:
            branches:
              only:
                - master
